kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main

steps:
  - name: update
    image: alpine:3.17
    pull: always
    commands:
      - echo "I am appleboy" > test.txt

  - name: push
    image: ghcr.io/appleboy/drone-git-push:latest
    pull: always
    settings:
      author_email: "actions@github.com"
      author_name: GitHub Actions
      branch: main
      commit: true
      commit_message: "[skip ci] Updated translations"
      remote: "git@github.com:go-training/drone-git-push-example.git"
      ssh_key:
        from_secret: git_push_ssh_key
