name: Lint and Testing

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: update some text
        run: |
          openssl rand -hex 16 > test.txt

      - name: git push changes
        uses: appleboy/git-push-action@main
        with:
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: GitHub Actions
          branch: main
          commit: true
          commit_message: "[skip ci] Updated changes from github actions"
          remote: git@github.com:go-training/drone-git-push-example.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}

      - name: update some text 2
        run: |
          openssl rand -hex 16 > test.txt

      - name: git push changes 2
        uses: appleboy/git-push-action@main
        with:
          branch: main
          commit: true
          commit_message: "[skip ci] Updated changes default user"
          remote: git@github.com:go-training/drone-git-push-example.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}

      - name: update some text 3
        run: |
          openssl rand -hex 16 > test.txt

      - name: git push changes 3
        uses: appleboy/git-push-action@main
        with:
          author_email: teabot@gitea.io
          author_name: GiteaBot
          branch: main
          commit: true
          commit_message: "[skip ci] Updated changes by gitea bot"
          remote: git@github.com:go-training/drone-git-push-example.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}
