name: Lint and Testing

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: update some text
        run: |
          echo "I am appleboy" > test.txt

      - name: Configure git to trust the workspace despite the different owner
        run:
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: git push changes
        uses: appleboy/git-push-action@main
        with:
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: GitHub Actions
          branch: main
          commit: true
          commit_message: "[skip ci] Updated changes from github actions"
          remote: git@github.com:go-training/drone-git-push-example.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}

