name: Lint and Testing

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: update some text
        run: |
          echo "I am appleboy" > test.txt

      - name: git push changes
        uses: appleboy/git-push-action@main
        with:
          author_email: "actions@github.com"
          author_name: GitHub Actions
          branch: main
          commit: true
          commit_message: "[skip ci] Updated changes from github actions"
          remote: https://appleboy:${{ secrets.GITHUB_TOKEN }}@github.com/go-training/drone-git-push-example.git

